### ISSUE TITLE
Packaging ChatBot UI for self-hosting on Umbrel

### ISSUE THREAD

**Issue by nmfretz** [mckaywrigley/chatbot-ui#124]
Hey @mckaywrigley, fantastic work on ChatBot UI! I have been using a self-hosted version of this and absolutely love it.

Would you be interested in packaging ChatBot UI to run on [Umbrel](https://umbrel.com/)? We are an OS for running a personal server in your home to self-host open source apps. You can see the apps currently on our App Store here: https://apps.umbrel.com/.

Apps on Umbrel run in docker containers, so ChatBot UI is pretty much ready to go as-is. Here is what is needed to get ChatBot UI on our app store (I can help with every stage of this):
1) build and push an amd64 & arm64 multi-arch Docker image to the Docker registry. This would need to include a version tag so that it looks something like: `mckaywrigley/chatbot-ui:v0.1.0`.
- If you are interested, I can open a PR that adds a GitHub workflow to automatically build and push a multi-arch image on tag.
2) Open a PR to https://github.com/getumbrel/umbrel-apps with a new `chatbot-ui` directory containing a `docker-compose.yml` and `umbrel-app.yml`
- The docker-compose.yml would look like this:
```yml
version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: chatbot-ui_web_1
      APP_PORT: 3000

  web:
    image: mckaywrigley/chatbot-ui:v<your-version-here>@sha256:<multi-arch-digest-here>
```

- The `umbrel-app.yml` could look like this with any changes to wording that you want.
```yml
manifestVersion: 1
id: chatbot-ui
category: Productivity
name: ChatBot UI
version: "<your-version-here>"
tagline: ChatGPT but better
description: >-
  ChatBot UI is an advanced chatbot kit for OpenAI's chat models aiming to mimic ChatGPT's interface and functionality.

  Simply add your OpenAI API key and start chatting!

  This version of ChatBot UI supports both GPT-3.5 and GPT-4 models. Conversations are stored locally within your browser.
  You can export and import conversations to safeguard against data loss.
developer: Mckay Wrigley
website: https://github.com/mckaywrigley/chatbot-ui
dependencies: []
repo: https://github.com/mckaywrigley/chatbot-ui
support: https://github.com/mckaywrigley/chatbot-ui/issues
port: 10101
gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
path: ""
defaultUsername: ""
defaultPassword: ""
submitter: Mckay Wrigley
submission: https://github.com/getumbrel/umbrel-apps/pull/<your PR #>
```

3) Create gallery images and icon. See here for example: https://apps.umbrel.com/app/nostr-relay.
- I can help with these. We can create something for your approval or you can provide some screenshots and text that we can use.
