### ISSUE TITLE
Feature Request: deploy using docker compose

### ISSUE THREAD

**Issue by TiancongLx** [mckaywrigley/chatbot-ui#1594]

**Comment by ChadMoran** [comment]
I would sponsor this.

**Comment by popaurel** [comment]
There is a docker compose in the LocalAI repo you could copy from:
https://github.com/mudler/LocalAI/blob/master/examples/chatbot-ui/docker-compose.yaml

For example:

```
version: '3.6'

services:
  chatbot-ui:
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    ports:
      - 3000:3000
    environment:
      - 'OPENAI_API_KEY=sk-XXXXXXXXXXXXXXXXXXXX'
```
