### ISSUE TITLE
Feature Request: Allow to connect to other APIs

### ISSUE THREAD

**Issue by mkellerman** [mckaywrigley/chatbot-ui#432]
Here is the docker compose file i'm using to deploy chatbot-ui and llama-cli api:

```
version: '3.6'

services:
  chatgpt:
    build: .
    # image: ghcr.io/mckaywrigley/chatbot-ui:main
    ports:
      - 9080:3000
    environment:
      - 'OPENAI_API_KEY='
      - 'OPENAI_API_HOST=http://api:8080'

  api:
    image: quay.io/go-skynet/llama-cli:v0.4
    volumes:
      - /Users/Shared/Models:/models
    ports:
      - 9000:8080
    environment:
      - MODEL_PATH=/models/7B/gpt4all-lora-quantized.bin
      - CONTEXT_SIZE=700
      - THREADS=4
    command: api
```

Unfortunatly, it doesn't work out of the box. And not sure if the front end should connect to 'any' API, or the api should mimic the api endpoints of openapi so it works seamlessly.

But will cross post in both repos.
