### ISSUE TITLE
Some environment variables from compose are ignored

### ISSUE THREAD

**Issue by Xav-Pe** [mckaywrigley/chatbot-ui#535]
Hi,

I try to edit ``NEXT_PUBLIC_DEFAULT_TEMPERATURE`` and ``NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT`` (as renamed in [this commit](https://github.com/mckaywrigley/chatbot-ui/commit/ea1d09244acc3c94a87a3658b1ee271542c6fecf#diff-110077186eda23f5a76bd65631d9689184e89b97b96806abc2b05d15c8e42624)) in compose.yaml : 

```yaml
services:
  chat:
    container_name: chatbot-ui
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    environment:
      TZ: 'Europe/Paris'
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_ORGANIZATION: MYORG
      NEXT_PUBLIC_DEFAULT_TEMPERATURE: 0.5
      NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT: Answer as if you were a duck
```

The ``OPENAI_API_KEY`` variable is correctly read, but ``NEXT_PUBLIC_DEFAULT_TEMPERATURE`` and ``NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT`` are ignored. 

I thinks it was supposed to be fixed by this issue https://github.com/mckaywrigley/chatbot-ui/issues/388 but it seems it's still broken.

Thanks for the good work anyway.
