### ISSUE TITLE
Publish Docker Image

### ISSUE THREAD

**Issue by d1vanloon** [mckaywrigley/chatbot-ui#92]
# Summary

Add a CI step to build and publish the docker image for this repo to the GitHub package registry.

# Details

Use GitHub Actions to define a build/deploy step that runs on each commit to the `main` branch. The CI step should build the docker image and publish it to the GitHub package repository for this repo under both a tag with the short commit hash, as well as the `latest` tag.

This would allow users to pull an already-built docker image from the registry and enable easier use and integration of new changes in hosted docker environments.

**Comment by d1vanloon** [comment]
Would you be open to a PR that adds this functionality?

**Comment by ItsNoted** [comment]
I built one here

```
version: "3.9"
services:
  web:
    image: itsnoted/chatpad:latest
    container_name: chatpad
    ports:
      - "8200:80"
```

https://hub.docker.com/r/itsnoted/chatpad
